-- 서브쿼리 사용
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM FOOD_PRODUCT
WHERE price = (SELECT MAX(PRICE) FROM FOOD_PRODUCT)
-- 오름차순 정렬 후 LIMIT 사용 
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, PRICE
FROM FOOD_PRODUCT
ORDER BY PRICE DESC LIMIT 1




