-- 틀린 코드
-- SELECT HOUR(DATETIME) AS HOUR, 
-- FROM ANIMAL_OUTS
-- GROUP BY HOUR(DATETIME) HAVING HOUR BETWEEN '0' AND '23' 
-- ORDER BY HOUR

-- SET 사용한 코드
SET @HOUR = -1;

SELECT (@HOUR := @HOUR + 1) as HOUR,
(SELECT COUNT(*) FROM ANIMAL_OUTS WHERE HOUR(DATETIME) = @HOUR) as COUNT
FROM ANIMAL_OUTS
WHERE @HOUR < 23